[workspace]
allow_dirty         = false
dependencies_update = false
semver_check        = true

[[package]]
name    = "cova-algebra"
publish = true

[[package]]
name    = "cova-space"
publish = true

[[package]]
name    = "cova"
publish = true
