[book]
authors     =["Harness Lab"]
language    ="en"
multilingual=false
src         ="."
title       ="Harness: Mathematical Abstractions and Computations"
description ="Harness is a Rust ecosystem for mathematical abstractions and computations, focusing on rigorous implementations of mathematical structures and algorithms."

[build]
build-dir                ="docs"
create-missing           =true
use-default-preprocessors=false

[preprocessor.links]

[preprocessor.katex]
after=["links"]

[output.linkcheck]
follow-web-links=false # TODO (autoparallel): fix this
traverse-parent-directories=true
warning-policy="ignore"

# TODO (autoparallel): there's a bunch to fix with this
# [preprocessor.keeper]
# command     ="mdbook-keeper"

[output.html]
default-theme       ="dark"
preferred-dark-theme="ayu"
git-repository-url  ="https://github.com/harness-lab/harness"

[output.html.playground]
editable=true
runnable=true

[rust]
edition="2021"