[package]
name = "harness-space"

authors     = ["Harness Labs"]
description = "The library for topological and other spaces"
edition     = "2021"
keywords    = ["mathematics", "topology"]
license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/harness-labs/space"
version     = "0.1.0"

[dependencies]
itertools = { workspace = true }
num       = { workspace = true }
